Update Services examples
micro-ROS/micro-ROS-demos pull request #31
Opened 2020-11-10 09:32 UTC by pablogs9

Before merge:

- [ ] https://github.com/micro-ROS/rclc/pull/44

2020-11-10 16:37 UTC, JanStaschulat commented on rclc/addtwoints_client/main.c
> +  rcl_client_t client;
```suggestion
  rcl_client_t client = rcl_get_zero_initialized_client();
```

2020-11-10 16:38 UTC, JanStaschulat commented on rclc/addtwoints_client/main.c
> +void client_callback(void * msg, rmw_request_id_t * req_id){
```suggestion
void client_callback(const void * msg, rmw_request_id_t * req_id){
```

2020-11-10 16:40 UTC, JanStaschulat commented on rclc/addtwoints_client/main.c
>  {
```suggestion
{
    RCLC_UNUSED(argc);
    RCLC_UNUSED(argv);
```

2020-11-10 16:41 UTC, JanStaschulat commented on rclc/addtwoints_server/main.c
> +typedef void (* rclc_service_callback_t)(const void *, rmw_request_id_t *, void *);
should not be necessary.

2020-11-10 16:42 UTC, JanStaschulat commented on rclc/addtwoints_server/main.c
> +  rcl_allocator_t allocator = rcl_get_default_allocator();
```suggestion
  RCLC_UNUSED(argc);
  RCLC_UNUSED(argv);
  rcl_allocator_t allocator = rcl_get_default_allocator();
```

2020-11-10 16:43 UTC, JanStaschulat commented on rclc/addtwoints_server/main.c
> +  rcl_service_t service;
```suggestion
  rcl_service_t service = rcl_get_zero_initialized_service();
```

2020-11-10 16:44 UTC, JanStaschulat requested changes
Initialization of service/client
const void pointer - first argument of client_callback
compiler warnings -  unused arguments

2020-11-11 06:26 UTC, pablogs9 commented
All addressed

2020-11-11 10:06 UTC, JanStaschulat approved these changes

2020-11-25 08:26 UTC, merged